name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight
  workflow_dispatch:      # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push snake svg to the profile repo
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: "chore: update github contribution grid snake"
          add: 'dist/*.svg'
